# Generated by Django 4.2.4 on 2023-08-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_pictures/'),
        ),
    ]
