# Generated by Django 4.2.4 on 2023-08-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='img',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
